"""descrição da migração

Revision ID: 0e839038cb59
Revises: 
Create Date: 2024-11-03 17:29:23.969567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e839038cb59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumo_frigobar')
    op.drop_table('cancelamento')
    op.drop_table('quarto')
    op.drop_table('acompanhante')
    op.drop_table('hospede')
    op.drop_table('reserva')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('idreserva', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idhospede', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codquarto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('datainicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('datafim', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valordesconto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['codquarto'], ['quarto.codquarto'], name='reserva_codquarto_fkey'),
    sa.ForeignKeyConstraint(['idhospede'], ['hospede.idhospede'], name='reserva_idhospede_fkey'),
    sa.PrimaryKeyConstraint('idreserva', name='reserva_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('hospede',
    sa.Column('idhospede', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idpessoa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idpessoa'], ['pessoa.idpessoa'], name='hospede_idpessoa_fkey'),
    sa.PrimaryKeyConstraint('idhospede', name='hospede_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('acompanhante',
    sa.Column('idacompanhante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idpessoa', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idhospede', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idhospede'], ['hospede.idhospede'], name='acompanhante_idhospede_fkey'),
    sa.ForeignKeyConstraint(['idpessoa'], ['pessoa.idpessoa'], name='acompanhante_idpessoa_fkey'),
    sa.PrimaryKeyConstraint('idacompanhante', name='acompanhante_pkey')
    )
    op.create_table('quarto',
    sa.Column('codquarto', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_quarto', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('qtdcamas', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('frigobar', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('banheira', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('codquarto', name='quarto_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cancelamento',
    sa.Column('idcancelamento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idreserva', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datacancelamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idreserva'], ['reserva.idreserva'], name='cancelamento_idreserva_fkey'),
    sa.PrimaryKeyConstraint('idcancelamento', name='cancelamento_pkey')
    )
    op.create_table('consumo_frigobar',
    sa.Column('idconsumo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idreserva', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idreserva'], ['reserva.idreserva'], name='consumo_frigobar_idreserva_fkey'),
    sa.PrimaryKeyConstraint('idconsumo', name='consumo_frigobar_pkey')
    )
    # ### end Alembic commands ###
